name: Deploy React App for Ops

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: echo "${{ secrets.OPS_ENV_FILE }}" > .env

      - name: Install & Build
        run: |
          yarn install
          yarn build


      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.OPS_HOST }}
          username: ${{ secrets.OPS_USER }}
          key: ${{ secrets.OPS_SSH_KEY }}
          source: "dist"
          target: /srv/admin/current/
          strip_components: 1
